server:
  port: 8081
spring:
  kafka:
    consumer:
      bootstrap-servers: locahost:9092
      group-id: es_assignment
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/es_assignment?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: username
    password: password
    dbcp2:
      default-query-timeout: 300
    output:
      ansi:
        enabled: always

# elasticsearch
elasticsearch:
  hosts: http://localhost:9200